### PR TITLE
update Makefile

### PR DESCRIPTION
**Pull request by animegasan**
Fix bug include

1. cloudflared
2. luci-app-cloudflared
3. luci-app-ipinfo

### CODE REVIEW

**Review by armarchindo — APPROVED** [review]

**Review by armarchindo — APPROVED** [review]

**Review by armarchindo — APPROVED** [review]

**Review by armarchindo — CHANGES_REQUESTED** [review]
kurang ` / ` bro, ` $(TOPDIR)/xxx/xxx `

**Comment by animegasan** [comment]
> kurang `/` bro, `$(TOPDIR)/xxx/xxx`

Itu ada 4 commit, harusnya 3 kwkwkwkw

**Comment by armarchindo** [comment]
> > kurang `/` bro, `$(TOPDIR)/xxx/xxx`
> 
> Itu ada 4 commit, harusnya 3 kwkwkwkw

wakakakakakka, sementara package cloudflare tak nonaktifkan dulu,, ada beberapa aarch yang bentrok hahaha

**Comment by armarchindo** [comment]
sipp,, udah aman, thanks mbah

**Pull request closed without merging**
